# Site settings
title: Prachi Pathak | Salesforce Developer
description: Salesforce Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Prachi Pathak
user_description: Hello, Greetings Reader! <br> <br> I am Prachi, <a href="https://www.salesforce.com/trailblazer/ppathak1" target="blank"> 7x Salesforce Certified </a> Developer spaning over 5+ years of experience in IT and on Salseforce.com platform - Admin Configuration, Customization (Apex, LWC, Integration) and SOQL. I have worked across various domains which includes biopharmaceutical, insurance, oil and banking. I've worked in Sales and Service cloud. 
user_title: Salesforce Developer
email: 
linkedIn _username: 
trailhead_username:
github_username: 
download_cv:


# Google-analytics
#google-analytics:
  #id: ""

exclude: ['package.json', 'src' , 'node_modules']
